'use client'

import { useMemo, useState } from 'react'
import { markImagingOrderPaid } from '@/lib/actions/imaging'

type Row={imaging_order_id:string;patient_name:string;name_en:string;name_fr:string;modality:string;charge_amount_xaf:number|null;charge_balance_xaf:number;charge_status:string|null;order_status:string;item_status:string}
type Group={id:string;patient:string;items:Row[];total:number;balance:number;allPaid:boolean;status:string}
export default function ImagingCashierVerification({rows,lang}:{rows:Row[];lang:'fr'|'en'}){
 const fr=lang==='fr'; const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null)
 const groups=useMemo<Group[]>(()=>{const m=new Map<string,Group>();for(const r of rows){let g=m.get(r.imaging_order_id);if(!g){g={id:r.imaging_order_id,patient:r.patient_name,items:[],total:0,balance:0,allPaid:true,status:r.order_status};m.set(r.imaging_order_id,g)}g.items.push(r);g.total+=Number(r.charge_amount_xaf||0);g.balance+=Number(r.charge_balance_xaf||0);g.allPaid=g.allPaid&&Number(r.charge_balance_xaf||0)<=0}return [...m.values()]},[rows])
 const total=rows.reduce((s,r)=>s+Number(r.charge_amount_xaf||0),0), outstanding=rows.reduce((s,r)=>s+Number(r.charge_balance_xaf||0),0)
 const sync=async(id:string)=>{setBusy(id);setMessage(null);const r=await markImagingOrderPaid(id);if('error'in r&&r.error)setMessage(r.error);else setMessage(fr?'Statut d’imagerie synchronisé.':'Imaging payment status synchronized.');setBusy(null)}
 return <div style={{background:'var(--color-surface)',border:'1px solid var(--color-border)',borderRadius:'var(--radius-md)',padding:14,marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><h2 style={{fontSize:14,margin:0}}>{fr?'Vérification caisse — imagerie':'Cashier verification — imaging'}</h2><p style={{fontSize:11,color:'var(--color-text-secondary)',margin:'3px 0 0'}}>{fr?'Chaque examen d’imagerie doit avoir une charge financière traçable.':'Every imaging examination must have a traceable financial charge.'}</p></div><div style={{fontSize:11,fontFamily:'var(--font-mono)'}}>{groups.length} orders · {total.toLocaleString()} FCFA</div></div>{message&&<p style={{fontSize:11,color:'var(--color-success-text)',margin:'8px 0'}}>{message}</p>}<div style={{display:'grid',gap:6,marginTop:10}}>{groups.map(g=><div key={g.id} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:10,alignItems:'center',padding:'8px 0',borderTop:'1px solid var(--color-border-subtle)'}}><div><strong style={{fontSize:12}}>{g.patient}</strong><div style={{fontSize:10,color:'var(--color-text-secondary)'}}>{g.items.map(i=>fr?i.name_fr:i.name_en).join(' · ')}</div><div style={{fontSize:9,color:'var(--color-text-secondary)'}}>{g.items.length} {fr?'examen(s)':'exam(s)'} · {g.status}</div></div><div style={{fontSize:11,fontFamily:'var(--font-mono)',textAlign:'right'}}>{g.balance>0?`${g.balance.toLocaleString()} due`:fr?'Payé':'Paid'}<div style={{fontSize:9,color:'var(--color-text-secondary)'}}>{g.total.toLocaleString()} FCFA</div></div>{g.allPaid&&g.status!=='paid'&&g.status!=='completed'?<button disabled={busy===g.id} onClick={()=>sync(g.id)} style={{padding:'6px 8px',fontSize:10,border:'1px solid var(--color-border)',background:'transparent',borderRadius:'var(--radius-sm)',cursor:'pointer'}}>{busy===g.id?'…':fr?'Synchroniser':'Sync paid status'}</button>:<span/>}</div>)}</div>{outstanding>0&&<p style={{fontSize:11,color:'var(--color-warning-text)',margin:'10px 0 0'}}>{fr?`${outstanding.toLocaleString()} FCFA restent à encaisser pour l’imagerie.`:`${outstanding.toLocaleString()} FCFA remain outstanding for imaging.`}</p>}</div>
}
