'use client'

import { useMemo, useState } from 'react'
import { markImagingOrderPaid } from '@/lib/actions/imaging'

type Row={imaging_order_id:string;patient_name:string;name_en:string;name_fr:string;modality:string;charge_amount_xaf:number|null;charge_balance_xaf:number;charge_status:string|null;order_status:string;item_status:string}
export default function ImagingCashierVerification({rows,lang}:{rows:Row[];lang:'fr'|'en'}){
 const fr=lang==='fr'; const [busy,setBusy]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null)
 const groups=useMemo(()=>{const m=new Map<string,Row>();for(const r of rows){if(!m.has(r.imaging_order_id))m.set(r.imaging_order_id,r)}return [...m.values()]},[rows])
 const total=rows.reduce((s,r)=>s+Number(r.charge_amount_xaf||0),0), outstanding=rows.reduce((s,r)=>s+Number(r.charge_balance_xaf||0),0)
 const sync=async(id:string)=>{setBusy(id);setMessage(null);const r=await markImagingOrderPaid(id);if('error'in r&&r.error)setMessage(r.error);else setMessage(fr?'Statut d’imagerie synchronisé.':'Imaging payment status synchronized.');setBusy(null)}
 return <div style={{background:'var(--color-surface)',border:'1px solid var(--color-border)',borderRadius:'var(--radius-md)',padding:14,marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><h2 style={{fontSize:14,margin:0}}>{fr?'Vérification caisse — imagerie':'Cashier verification — imaging'}</h2><p style={{fontSize:11,color:'var(--color-text-secondary)',margin:'3px 0 0'}}>{fr?'Chaque examen d’imagerie doit avoir une charge financière traçable.':'Every imaging examination must have a traceable financial charge.'}</p></div><div style={{fontSize:11,fontFamily:'var(--font-mono)'}}>{groups.length} orders · {total.toLocaleString()} FCFA</div></div>{message&&<p style={{fontSize:11,color:'var(--color-success-text)',margin:'8px 0'}}>{message}</p>}<div style={{display:'grid',gap:6,marginTop:10}}>{groups.map(r=><div key={r.imaging_order_id} style={{display:'grid',gridTemplateColumns:'1fr auto auto',gap:10,alignItems:'center',padding:'8px 0',borderTop:'1px solid var(--color-border-subtle)'}}><div><strong style={{fontSize:12}}>{r.patient_name}</strong><div style={{fontSize:10,color:'var(--color-text-secondary)'}}>{fr?r.name_fr:r.name_en} · {r.modality}</div></div><div style={{fontSize:11,fontFamily:'var(--font-mono)',textAlign:'right'}}>{Number(r.charge_balance_xaf)>0?`${Number(r.charge_balance_xaf).toLocaleString()} due`:fr?'Payé':'Paid'}<div style={{fontSize:9,color:'var(--color-text-secondary)'}}>{r.charge_status??'—'} · {r.order_status}</div></div>{Number(r.charge_balance_xaf)<=0&&r.order_status!=='paid'&&r.order_status!=='completed'?<button disabled={busy===r.imaging_order_id} onClick={()=>sync(r.imaging_order_id)} style={{padding:'6px 8px',fontSize:10,border:'1px solid var(--color-border)',background:'transparent',borderRadius:'var(--radius-sm)',cursor:'pointer'}}>{busy===r.imaging_order_id?'…':fr?'Synchroniser':'Sync paid status'}</button>:<span/>}</div>)}</div>{outstanding>0&&<p style={{fontSize:11,color:'var(--color-warning-text)',margin:'10px 0 0'}}>{fr?`${outstanding.toLocaleString()} FCFA restent à encaisser pour l’imagerie.`:`${outstanding.toLocaleString()} FCFA remain outstanding for imaging.`}</p>}</div>
}
