import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { getCurrentStaff } from '@/lib/auth/getCurrentStaff'
import OwnerFinancialDashboard from '@/components/OwnerFinancialDashboard'
import ImagingRevenueCard from '@/components/ImagingRevenueCard'
function doualaDateString(daysAgo=0){const d=new Date();d.setUTCHours(d.getUTCHours()+1);d.setUTCDate(d.getUTCDate()-daysAgo);return d.toISOString().slice(0,10)}
export default async function FinancialPage(){
 const staff=await getCurrentStaff();if(staff.role!=='admin')redirect('/dashboard');const supabase=await createClient();const today=doualaDateString()
 const [revenueResult,methodsResult,cashiersResult,categoriesResult,outstandingResult,complianceResult,reconciliationResult,shiftsResult,salesResult,imagingResult]=await Promise.all([
  supabase.rpc('clinic_daily_revenue',{p_clinic_id:staff.clinicId,p_days:30}),supabase.rpc('eod_revenue_by_method',{p_clinic_id:staff.clinicId,p_date:today}),supabase.rpc('eod_revenue_by_cashier',{p_clinic_id:staff.clinicId,p_date:today}),supabase.rpc('eod_revenue_by_category',{p_clinic_id:staff.clinicId,p_date:today}),supabase.rpc('outstanding_balance_summary',{p_clinic_id:staff.clinicId}),supabase.rpc('compliance_pending_summary',{p_clinic_id:staff.clinicId}),supabase.from('pos_daily_reconciliations').select('reconciliation_date,cash_counted_xaf,momo_counted_xaf,orange_money_counted_xaf,notes,reconciled_at').eq('clinic_id',staff.clinicId).eq('reconciliation_date',today).maybeSingle(),supabase.from('cashier_shifts').select('id,staff_id,variance_xaf,expected_cash_xaf,closing_cash_xaf,closed_at').eq('clinic_id',staff.clinicId).eq('status','closed').eq('requires_review',true).order('closed_at',{ascending:false}).limit(10),supabase.from('pos_sales').select('id,created_at,payment_method,total_amount_xaf,sold_by').eq('clinic_id',staff.clinicId).eq('status','completed').order('created_at',{ascending:false}).limit(15),supabase.from('imaging_work_queue').select('ordered_at,charge_amount_xaf,charge_balance_xaf,charge_status').eq('clinic_id',staff.clinicId).not('charge_amount_xaf','is',null).order('ordered_at',{ascending:true})
 ])
 const outstanding=outstandingResult.data?.[0],compliance=complianceResult.data?.[0],shifts=shiftsResult.data??[],sales=salesResult.data??[];const staffIds=[...new Set([...shifts.map(r=>r.staff_id),...sales.map(r=>r.sold_by)].filter(Boolean))];const {data:staffRows}=staffIds.length?await supabase.from('staff').select('id,full_name').in('id',staffIds):{data:[] as any[]};const staffNames=new Map((staffRows??[]).map(r=>[r.id,r.full_name]));const expectedByMethod:Record<string,number>={};for(const r of methodsResult.data??[])expectedByMethod[r.method]=Number(r.total_xaf||0)
 const imagingMap=new Map<string,{billed_xaf:number;collected_xaf:number;exams:number}>();for(const r of imagingResult.data??[]){const date=String(r.ordered_at).slice(0,10);const x=imagingMap.get(date)??{billed_xaf:0,collected_xaf:0,exams:0};if(r.charge_status!=='reversed'){x.billed_xaf+=Number(r.charge_amount_xaf||0);x.collected_xaf+=Math.max(0,Number(r.charge_amount_xaf||0)-Number(r.charge_balance_xaf||0));x.exams+=1}imagingMap.set(date,x)}const imagingRows=[...imagingMap.entries()].slice(-30).map(([date,v])=>({date,billed_xaf:v.billed_xaf,collected_xaf:v.collected_xaf,exams:v.exams}))
 return <div><OwnerFinancialDashboard lang={staff.preferredLanguage} revenue30={(revenueResult.data??[]).map(r=>({report_date:r.report_date,revenue_xaf:Number(r.revenue_xaf||0),transaction_count:Number(r.transaction_count||0)})).reverse()} todayMethods={(methodsResult.data??[]).map(r=>({method:r.method,total_xaf:Number(r.total_xaf||0),transaction_count:Number(r.transaction_count||0)}))} todayCashiers={(cashiersResult.data??[]).map(r=>({staff_id:r.staff_id,staff_name:r.staff_name,total_xaf:Number(r.total_xaf||0),cash_xaf:Number(r.cash_xaf||0),transaction_count:Number(r.transaction_count||0)}))} todayCategories={(categoriesResult.data??[]).map(r=>({category:r.category,total_xaf:Number(r.total_xaf||0)}))} recentSales={sales.map(r=>({id:r.id,created_at:r.created_at,payment_method:r.payment_method,total_amount_xaf:Number(r.total_amount_xaf||0),sold_by_name:staffNames.get(r.sold_by)??'—'}))} variances={shifts.map(r=>({id:r.id,staff_name:staffNames.get(r.staff_id)??'—',variance_xaf:Number(r.variance_xaf||0),expected_cash_xaf:Number(r.expected_cash_xaf||0),closing_cash_xaf:Number(r.closing_cash_xaf||0),closed_at:r.closed_at}))} reconciliation={reconciliationResult.data?{reconciliation_date:reconciliationResult.data.reconciliation_date,cash_counted_xaf:Number(reconciliationResult.data.cash_counted_xaf||0),momo_counted_xaf:Number(reconciliationResult.data.momo_counted_xaf||0),orange_money_counted_xaf:Number(reconciliationResult.data.orange_money_counted_xaf||0),notes:reconciliationResult.data.notes,reconciled_at:reconciliationResult.data.reconciled_at}:null} todayExpectedByMethod={expectedByMethod} outstandingXaf={Number(outstanding?.total_outstanding_xaf||0)} overdueXaf={Number(outstanding?.overdue_outstanding_xaf||0)} unpaidChargeCount={Number(outstanding?.unpaid_charge_count||0)} pendingShiftReviews={Number(compliance?.pending_shift_variance_reviews||0)}/><ImagingRevenueCard rows={imagingRows} lang={staff.preferredLanguage}/></div>
}
