// lib/actions/consultation.ts
'use server'

import { createClient } from '@/lib/supabase/server'
import { getCurrentStaff } from '@/lib/auth/getCurrentStaff'
import { redirect } from 'next/navigation'

export interface CompleteConsultationResult { error?: string; alreadyCompleted?: boolean }
interface ConsultationDiagnosisInput { diagnosis: string; icd10Code: string | null; isPrimary: boolean; sequence: number }
function parseDiagnoses(formData: FormData): ConsultationDiagnosisInput[] {
  const raw = formData.get('diagnoses_json')
  if (typeof raw === 'string' && raw.trim()) { try { const parsed = JSON.parse(raw); if (Array.isArray(parsed)) return parsed.map((d:any,index:number)=>({ diagnosis: typeof d?.diagnosis==='string'?d.diagnosis.trim():'', icd10Code: typeof d?.icd10Code==='string'&&d.icd10Code.trim()?d.icd10Code.trim():null, isPrimary:Boolean(d?.isPrimary), sequence:Number.isInteger(d?.sequence)&&d.sequence>0?d.sequence:index+1 })).filter(d=>d.diagnosis.length>0) } catch {} }
  const diagnosis=(formData.get('diagnosis') as string)?.trim(); const diagnosisCode=(formData.get('diagnosis_code') as string)?.trim()
  return diagnosis?[{diagnosis,icd10Code:diagnosisCode||null,isPrimary:true,sequence:1}]:[]
}
export async function completeConsultation(visitId:string, consultationId:string, formData:FormData):Promise<CompleteConsultationResult>{
  const staff=await getCurrentStaff(); const supabase=await createClient()
  const {data:currentVisit}=await supabase.from('visits').select('status, patient_id, is_emergency').eq('id',visitId).single()
  if(currentVisit?.status!=='in_consultation') return {error:'Cette consultation a déjà été terminée — aucune action supplémentaire nécessaire.',alreadyCompleted:true}
  const diagnoses=parseDiagnoses(formData); const subjectiveNotes=(formData.get('subjective_notes') as string)?.trim(); const examinationNotes=(formData.get('examination_notes') as string)?.trim(); const treatmentPlan=(formData.get('treatment_plan') as string)?.trim(); const followupDate=(formData.get('followup_date') as string)?.trim()||null; const followupTime=(formData.get('followup_time') as string)?.trim()||null; const followupReason=(formData.get('followup_reason') as string)?.trim()||null
  if(diagnoses.length>0){let seen=false; diagnoses.forEach((d,i)=>{d.sequence=i+1;if(d.isPrimary&&!seen)seen=true;else if(d.isPrimary)d.isPrimary=false});if(!diagnoses.some(d=>d.isPrimary))diagnoses[0].isPrimary=true}
  const {error:consultationSaveError}=await supabase.rpc('save_consultation_diagnoses',{p_clinic_id:staff.clinicId,p_consultation_id:consultationId,p_staff_id:staff.staffId,p_subjective_notes:subjectiveNotes||null,p_examination_notes:examinationNotes||null,p_treatment_plan:treatmentPlan||null,p_diagnoses:diagnoses})
  if(consultationSaveError)return {error:`Impossible d'enregistrer la consultation : ${consultationSaveError.message}`}
  const productIds=formData.getAll('rx_product_id') as string[]; const freetextNames=formData.getAll('rx_freetext_name') as string[]; const doses=formData.getAll('rx_dose') as string[]; const frequencies=formData.getAll('rx_frequency') as string[]; const durations=formData.getAll('rx_duration_days') as string[]; const quantities=formData.getAll('rx_quantity') as string[]
  const validRows=productIds.map((productId,i)=>({productId:productId||null,freetextName:freetextNames[i]||null,dose:doses[i],frequency:frequencies[i],durationDays:durations[i],quantity:quantities[i]})).filter(r=>(r.productId||r.freetextName)&&r.quantity); const hasPrescription=validRows.length>0
  if(hasPrescription){const {data:prescription,error:prescriptionError}=await supabase.from('prescriptions').insert({clinic_id:staff.clinicId,visit_id:visitId,consultation_id:consultationId,doctor_id:staff.staffId}).select('id').single();if(prescriptionError||!prescription)return {error:"Impossible de créer l'ordonnance. Réessayez."};const {error:itemsError}=await supabase.from('prescription_items').insert(validRows.map(r=>({prescription_id:prescription.id,product_id:r.productId,drug_name_freetext:r.freetextName,dose:r.dose||null,frequency:r.frequency||null,duration_days:r.durationDays?parseInt(r.durationDays,10):null,quantity_prescribed:parseInt(r.quantity,10)})));if(itemsError)return {error:"Ordonnance créée, mais certains médicaments n'ont pas pu être ajoutés."}}
  const panelIds=formData.getAll('lab_panel_ids') as string[];const testIds=formData.getAll('lab_test_ids') as string[];const externalNames=formData.getAll('lab_external_names') as string[];const labItems=[...panelIds.map(id=>({type:'panel',panel_id:id})),...testIds.map(id=>({type:'individual_test',catalog_id:id})),...externalNames.map(name=>({type:'external',name}))];const hasAnyLabItems=labItems.length>0;const hasInHouseLabOrder=panelIds.length>0||testIds.length>0
  if(hasAnyLabItems){const requestedMode=(formData.get('lab_billing_mode') as string)||'pay_now';const labBillingMode=currentVisit.is_emergency?'charge_to_encounter':requestedMode;const {data:orderResult,error:orderError}=await supabase.rpc('create_lab_order',{p_clinic_id:staff.clinicId,p_visit_id:visitId,p_ordered_by:staff.staffId,p_items:labItems,p_billing_mode:labBillingMode});if(orderError||!orderResult?.[0])return {error:`Impossible de créer la demande d'examen : ${orderError?.message??'erreur inconnue'}`};const chargeIds=orderResult[0].service_charge_ids as string[];if(chargeIds?.length&&labBillingMode==='pay_now'){const {error:invoiceError}=await supabase.rpc('open_invoice_for_charges',{p_service_charge_ids:chargeIds,p_created_by:staff.staffId});if(invoiceError)return {error:"Examens commandés, mais la facture n'a pas pu être créée."}}}
  const procedureIds=formData.getAll('procedure_ids') as string[];if(procedureIds.length>0&&currentVisit.patient_id)for(const procedureId of procedureIds){const {error}=await supabase.rpc('add_consultation_procedure_charge',{p_clinic_id:staff.clinicId,p_patient_id:currentVisit.patient_id,p_visit_id:visitId,p_service_price_id:procedureId,p_created_by:staff.staffId});if(error)return {error:`Impossible d'ajouter une procédure à la facture : ${error.message}`}}
  const admitPatient=formData.get('admit_patient')==='true';const admissionReason=(formData.get('admission_reason') as string)?.trim();if(admitPatient){if(!admissionReason)return {error:"Un motif d'admission est requis."};const {error}=await supabase.rpc('recommend_admission',{p_clinic_id:staff.clinicId,p_visit_id:visitId,p_recommended_by:staff.staffId,p_admission_reason:admissionReason});if(error)return {error:`Impossible de recommander l'admission : ${error.message}`}}
  const {error:completeError}=await supabase.rpc('complete_consultation',{p_visit_id:visitId,p_consultation_id:consultationId,p_staff_id:staff.staffId,p_has_prescription:hasPrescription,p_has_lab_order:hasInHouseLabOrder,p_has_admission:admitPatient});if(completeError)return {error:`Impossible de terminer la consultation : ${completeError.message}`}
  if(followupDate||followupTime){if(!followupDate||!followupTime)return {error:'La date et l’heure du suivi doivent être renseignées ensemble.'};const {error}=await supabase.rpc('schedule_followup_from_consultation',{p_visit_id:visitId,p_consultation_id:consultationId,p_doctor_id:staff.staffId,p_followup_date:followupDate,p_followup_time:followupTime,p_reason:followupReason});if(error)return {error:`Consultation terminée, mais le rendez-vous de suivi n'a pas pu être créé : ${error.message}`}}
  redirect('/dashboard')
}
